CMakeLists.txt
pkg-config.pc.cmake

This is required for when I get around to writing some Haskell bindings :-)

Added ability to auto-generate and install a keystone.pc file

---

suite/regress/c-crashers/crash-36-x64-execution-aborted.c
suite/regress/c-crashers/crash-37-x64-segfault-in-doit.c

* Add `crash-36-x64-execution-aborted.c`
* Add `crash-37-x64-segfault-in-doit.c`

Add two crash cases

---

bindings/haskell/samples/Sample.hs
bindings/haskell/src/Keystone/Internal/Util.hs

Removed unused utility functions and renamed some variables

Minor updates

---

suite/regress/x86_shifts.py

This test needs to be checked for correctness.

Regress test for SHR/SHL/SAR/SAL

---

suite/regress/x86_jmp_0x33_08.py

added regression test for "jmp 0x33, 08"

---

docs/COMPILE-WINDOWS.md
llvm/keystone/ks.cpp

use KS_ERR_NOMEM instead of -1.

fix memory leaks in ks_asm().

---

suite/regress/x64_sym_resolver.py

added regression test for sym_resolver

---

suite/regress/arm_bl_label.py

arm_bl_label_test_case

---

suite/regress/arm_blx_label.py
suite/regress/arm_blx_label_thumb.py

add arm_blx_label(_thumb) testcase

add arm_blx_label(_thumb) testcase

---

suite/regress/arm_bl_location.py

https://github.com/keystone-engine/keystone/issues/257

Adding unit test for arm_bl relative branch

---

suite/regress/mips_jal.py

mips jal test

---

llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCCodeEmitter.cpp

fix imm value in AArch64MCCodeEmitter::getLoadLiteralOpValue

---

CREDITS.TXT
bindings/README
bindings/csharp/README.md

As requested, I have updated contributors.
Also, I've fixed some issues with the README of c# binding.
Cheers
Marco

Updated contributors and fixed some issues with the guide of C# binding

---

llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp
llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCCodeEmitter.cpp

b.cond/cbz/cbnz/tbz/tbnz/adrp
for issuse #290

ARM64, fix issue for PC-relative offset

---

llvm/lib/Target/ARM/MCTargetDesc/ARMMCCodeEmitter.cpp
suite/regress/all_archs_branch_addr.py

Test/fix ARM Thumb B.W addresses

---

llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp

Issue #317 
A REX prefix byte must immediately precede the opcode byte or the
opcode escape byte. Emit segment override and address size prefix
bytes before a REX prefix byte.

Fix x86 instruction prefix ordering

---

llvm/lib/MC/MCParser/AsmParser.cpp

We can overflow the stack with a lot of exclamation...
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10433

Limit recursion in AsmParser::parsePrimaryExpr

---

kstool/kstool.cpp

Input from stdin was copied to the wrong buffer.

Fix input from stdin.

---

bindings/java/src/main/java/keystone/natives/DirectMappingKeystoneNative.java

Bug fix for win32 jna in java bindings.

---

bindings/haskell/keystone.cabal
bindings/haskell/src/Keystone.hs
bindings/haskell/src/Keystone/Internal/Core.chs
bindings/haskell/src/Keystone/Internal/Util.hs

Updates Haskell bindings with latest either package (removed deprecated module).

Update Haskell bindings

---

llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp

Cherry-pick https://reviews.llvm.org/D25112
