- bindings/python/keystone/keystone.py
- include/keystone/keystone.h
- llvm/keystone/ks.cpp
* ~~`ks_option`: The 'value' argument should have type `ks_opt_value`~~
* `ks_free`: The 'p' argument should have type `unsigned char*` to match the type of the 'encoding' argument to `ks_asm`
This doesn't change any functionality, but IMO is more "correct" (in regards to the type system) and adds clarity to the header file.
~~I've made minor adjustments to the different bindings, but I'm by no means an expert in most of those languages, so it would be good to have the original authors review and let me know if I've broken anything. Pinging @nl5887, @iksteen, and @sashs~~
> Changed argument types for ks_option and ks_free functions

- suite/regress/c-crashers/crash-38-x64-cast-ty-argument-of-incompatible-type.c
```
$ ./crash-38-x64-cast-ty-argument-of-incompatible-type
/path/to/llvm/include/llvm/Support/Casting.h:230: typename llvm::cast_retty<To, From>::ret_type llvm::cast(Y&) [with X = llvm::MCSectionELF; Y = llvm::MCSection; typename llvm::cast_retty<To, From>::ret_type = llvm::MCSectionELF&]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Aborted
```
> Add crash case: crash-38-x64-cast-ty-argument-of-incompatible-type.c

- bindings/python/keystone/keystone.py
In python 3 it was only possible to give a bytes string to asm (b'jmp esp'). If string was given to this function you got just the message "<wrong type>". Now you can give bytes or a string. 
If an KsError was raised and you wanted to cast it to str, another Error was raised, because ks_strerror returned an object of type bytes.
> python 2/3 compatibility in KsError.__str__ and Ks.asm

- bindings/go/keystone/samples/main.go
Update and Fix go binding sample.
- Currently, can't compiling because not found some of the const variables
- but I do not yet understand keystone C(++) side behavior. Please point out if I am wrong.
- `panic` built-in function always exit to the program. Remove else and export `ks` variable in the main function
> go: Update to latest keystone package API & Remove unnecessary else

- bindings/haskell/keystone.cabal
Same as Unicorn PR #637 (https://github.com/unicorn-engine/unicorn/pull/637).
Need to update the transformers dependency to get the Haskell bindings compiling with GHC 8.x
> [haskell bindings] Updated transformers dependency to work with GHC 8

- llvm/keystone/ks.cpp
- llvm/keystone/ks_priv.h
various members of the `ks_struct` ( `mode` and `sym_resolver`) were not initialized with default values and this causes undefined behavior (issue #250)
> initialize variables correctly in ks_struct. closes #250

- bindings/haskell/README.md
- bindings/haskell/keystone.cabal
- bindings/haskell/samples/Sample.hs
- bindings/haskell/src/Keystone.hs
- bindings/haskell/src/Keystone/CPU/Arm.chs
- bindings/haskell/src/Keystone/CPU/Arm64.chs
- bindings/haskell/src/Keystone/CPU/Hexagon.chs
- bindings/haskell/src/Keystone/CPU/Mips.chs
- bindings/haskell/src/Keystone/CPU/Ppc.chs
- bindings/haskell/src/Keystone/CPU/Sparc.chs
- bindings/haskell/src/Keystone/CPU/SystemZ.chs
- bindings/haskell/src/Keystone/CPU/X86.chs
- bindings/haskell/src/Keystone/Internal/Core.chs
- bindings/haskell/src/Keystone/Internal/Keystone.chs
- bindings/haskell/src/Keystone/Internal/Util.hs
Mainly style fixes.
I also changed the arguments to the `assemble` function so that it accepts a list of statements to assemble, rather than a single ";" or "\n" -separated string. This is more idiomatic Haskell.
> Updates to Haskell bindings

- docs/COMPILE-NIX.md
- docs/COMPILE-WINDOWS.md
LLVM_TARGETS_TO_BUILD should split with ';' not ','
> fix mistakes in docs

- docs/COMPILE-NIX.md
The 'fhs' build option has been renamed to 'lib64'
> Update nix compile docs to use lib64 option

- llvm/include/llvm/MC/MCObjectStreamer.h
- llvm/include/llvm/MC/MCStreamer.h
- llvm/lib/MC/MCObjectStreamer.cpp
- llvm/lib/MC/MCParser/AsmParser.cpp
- suite/regress/all_archs_value_directive.py
Bytes emitted by the Value directives in arm and ppc effects the follow up relative jumps. Added fixes to update address during asm parsing and also added a regression test for the specific case.
> Fix directive address update

- llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp
(b/bl/cbz/cbnz/tbz/tbnz/ldr/ldrsw/prfm)
> ARM64(llvm): Disable range checking on instructions with a PC-relative offset

- llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp
issue #269 
add jal operand type check to avoid `Inst.getOperand(0).getExpr()` assert fail.
> fixed Mips 'jal imm' segmentation fault

- llvm/lib/MC/MCParser/AsmParser.cpp
- suite/regress/x86_issue293.py
Removed a debug statement that was preventing correct errors from being thrown when bad instructions were followed by good instructions.
With the fix:
```
$ build/kstool/kstool x32 "jnz exit:; xor eax, eax; xor ebx, ebx"
ERROR: failed on ks_asm() with count = 0, error = 'Invalid operand (KS_ERR_ASM_INVALIDOPERAND)' (code = 512)
```
Without the fix:
```
$ build/kstool/kstool x32 "jnz exit:; xor eax, eax; xor ebx, ebx"
jnz exit:; xor eax, eax; xor ebx, ebx = [ 31 c0 31 db ]
```
Regression test with fix:
```
~/src/keystone$ suite/regress/x86_issue293.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK
```
Regression test without fix:
```
~src/keystone$ suite/regress/x86_issue293.py 
E …
```
> Fix issue #293

- bindings/python/setup.py
using `data_files` dict prefixed with `SITE_PACKAGES = os.path.join(get_python_lib(), "keystone")` is not portable. Regular setup configuration does not work, e.g., specifying `package_data` etc, since that only affects `sdist`.
The fix is a hack: customize `install_lib` to explicitly copy the file into keystone install dir.
This should fix #235 and #297 .
> fix python bindings shared library directory issue

- bindings/rust/README.md
Currently, the sample code in [/bindings/rust/README.md](https://github.com/keystone-engine/keystone/blob/master/bindings/rust/README.md) cannot be compiled.
I just copied the content of [/bindings/rust/examples/asm.rs](https://github.com/keystone-engine/keystone/blob/master/bindings/rust/examples/asm.rs) into the README.md and it can be compiled well.
> bindings: make the sample code in README.md for Rust compilable

- .gitignore
This is a meta data folder generated by Python's setuptools.
> Add *.egg-info to .gitignore

- bindings/python/keystone/keystone.py
When enabled, the assembled code will be returned as `bytes` (`str` on Python 2) instead of a list of integers, this is more memory efficient, faster (It's created using `ctypes.string_at` instead of a loop in Python), and more convenient since that's the type that most code that works with bytes in Python expects (That includes capstone).
Defaults to `False` for backwards compatibility, since changing the return type is a breaking change.
Please take into consideration whether this API is OK and if it indeed should default to `False`.
> Add asm(..., as_bytes=True) to Python bindings

- docs/README.md
The path /beyond_qemu.html should most likely be /beyond_llvm.html.
> Fix "Compare Keystone & LLVM" link

- llvm/keystone/ks.cpp
- llvm/lib/MC/MCParser/ELFAsmParser.cpp
- llvm/lib/Target/Hexagon/AsmParser/HexagonAsmParser.cpp
Fix some minor spelling errors in string constants.
> Fix minor spelling errors in libkeystone

- CMakeLists.txt
Default to hidden symbol visibility to reduce the number of public symbols in libkeystone.so. Reduces the number of defined public symbols from 2093 to 26.
There are still about 14 weak c++ symbols that I can't seem to figure out how to hide. They seem to all be related to instantiations of STL containers.
```
user@debian:~/keystone/build$ mkdir build && cd build && ../make-share.sh
...
user@debian:~/keystone/build$ readelf --dyn-syms llvm/lib/libkeystone.so.0 | grep -v ' 0 ' | wc -l
2093
user@debian:~/keystone/build$ readelf --dyn-syms llvm/lib/libkeystone.so.0 | grep -v ' 0 ' | grep -v 'WEAK' | wc -l
1805
```
```
user@debian:~/keystone/build$ mkdir build && cd build && ../make-share.sh
...
user@debian:~/keystone/build$ readelf --dyn-syms llvm/lib/libkeystone.so.0 | grep -v ' 0 ' | wc -l …
```
> Default to hidden symbol visibility

- CMakeLists.txt
- make-common.sh
- make-lib.sh
- make-share.sh
When compiling on linux, use GNUInstallDirs to automatically determine
the appropriate libdir path for multi-arch builds instead of hardcoding
lib/ or lib64/. GNUInstallDirs should follow the FHS appropriately for
non-debian platforms that place libs in lib64/. This also removes the
need to specify `lib64` on the command line when building for a
non-debian system that follows the linux FHS.
When compiling with cmake directly on debian and specifying
`-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_LIBRARY_ARCHITECTURE=<arch>`, the
libdir should be set to `/usr/lib/<arch>/`.
> Auto-detect install libdir to enable multi-arch debian builds

- debian/keystone-engine-dev.dirs
- debian/keystone-engine-dev.install
- debian/keystone-engine1.install
The new version of Ubuntu (and associated cmake, ...) puts the libraries in /usr/lib/x86_64-linux-gnu, breaking the existing packaging.
> Update Debian packaging to Ubuntu 18.04

- make-common.sh
- make-lib.sh
- make-share.sh
Starting Xcode 10 beta, there's no support for i386.
This commit changes the default build on iOS to regular libraries
instead of universal binaries.
Build of universal binaries is still supported with macos-universal.
> Don't build universal binaries by default

- llvm/include/llvm/ADT/SmallVector.h
Hello all,
This PR tries to make gcc 8 happy with its `class-memaccess` check, a similar fix has been [done](https://github.com/llvm-mirror/llvm/blob/master/include/llvm/ADT/SmallVector.h#L313) by LLVM.
> fix gcc's memaccess warning

- bindings/go/README.md
Sample for go binding on [README.md](https://github.com/keystone-engine/keystone/blob/master/bindings/go/README.md) is old. I fixed it.
> fix sample for go binding

- llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp
- llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCCodeEmitter.cpp
Currently, ADRP instructions on AArch64 will fail under some situations:
$ ./kstool/kstool arm64 "adrp   x2, #0x5C6000" 0x100
ERROR: failed on ks_asm() with count = 0, error = 'Unknown error' (code = 539)
This change fixes that (the change in AArch64AsmParser.cpp).
Additionally, this fixes an off-by-one error in AArch64MCCodeEmitter.cpp
**Before**
$ ./kstool/kstool arm64 "adrp   x2, #0x5C6000" 0x100
adrp   x2, #0x5C6000 = [ 22 2e 00 b0 ]
$ cstool arm64 "22 2e 00 b0" 0x100
100  22 2e 00 b0  adrp	x2, #0x5c5000
**After**
$ ./kstool/kstool arm64 "adrp   x2, #0x5C6000" 0x100
adrp   x2, #0x5C6000 = [ 22 2e 00 d0 ]
$ cstool arm64 "22 2e 00 d0" 0x100
100  22 2e 00 d0  adrp	x2, #0x5c6000
> Fix ADRP instruction encoding

- llvm/keystone/ks.cpp
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10437
Before it gets used in `AsmLexer::LexDigit`
> Sets a default radix

- bindings/python/setup.py
Now CMakeLIsts.txt uses suite/fuzz for fuzzing, and currently sdist command doesn't work due to this reason. After adding suite/, it worked.
I've used `python setup.py sdist bdist; pip wheel .` for building a wheel package, but I'm not sure if it's right. Thank you for the great project!
> add suite/ directory for suite/fuzz, fix python build

- bindings/rust/Cargo.toml
- bindings/rust/Makefile
- bindings/rust/README.md
- bindings/rust/keystone-sys/Cargo.toml
- bindings/rust/keystone-sys/build.rs
- bindings/rust/keystone-sys/src/lib.rs
- bindings/rust/src/lib.rs
Just various small cleanups which should ultimately enable us to publish a new version again (or at least fix compilation). (The last release is from [2016](https://crates.io/crates/keystone)) @nl5887 are you still maintaining these bindings or are you willing to pass on the crates.io publishing rights to someone else?
cc #399
> Various improvements to the Rust bindings

- bindings/python/debian/control
- bindings/python/debian/rules
- llvm/lib/MC/MCParser/AsmParser.cpp
This PR updates the Debian packaging so that it also builds a Python 3 deb.  It also addresses what appears to be a bug in the ASM parser which was identified by GCC.
> Update the Python binding's Debian packaging to build for Python 3

- docs/COMPILE.md
Keystone is available as a port in VCPKG , documenting the install process here will help users get started by providing a single set of commands to build Keystone, ready to be included in their projects.
VCPKG is a C++ library manager that simplifies installation for Keystone and other project dependencies, we also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.
> Add vcpkg installation instructions

- bindings/const_generator.py
- bindings/rust/keystone-sys/src/keystone_const.rs
- bindings/rust/keystone-sys/src/lib.rs
- bindings/rust/src/lib.rs
- A bool coming from C cannot be trusted; functionally it is a c_int,
and conversion to bool must be done by comparing to 0;
- similarly, a `#[repr(C)]` enum cannot be trusted to be a `u32`;
it is more often than not a `c_int`. This could cause breakage with
the ABI of the C functions of the binding. So the signatures and
enum definitions have been adapted based on the
`include/keystone/keystone.h` definitions.
- and most importantly: a ks_handle is a `ks_engine *` in C parlance,
and using `size_t` to represent it is not the right way. Moreover,
so doing prevents the `Sync` and `Send` traits from being
auto-unimplemented, meaning that this is implicitly asserting that
keystone is multithread-safe, even for the same instance. If that is
the case, then a `unsafe impl Sync for Keystone {}` …
> Fix Rust bindings

- bindings/go/keystone/keystone-binding.go
When trying to execute `make install` inside the go binding sample, the output shows an error that is specified by guitmz in issue #363 
Adding the missing cgo LDFLAGS resolves this issue.
> Update keystone-binding.go to fix issue #363

- debian/rules
This change provides parallel building for debian-family packaging
if someone wants to stay single job building(`-j1`), they are also able to use `export DEB_BUILD_OPTIONS="parallel=1"` command to stay on.
> Debian Packaging: Let debuild support parallel building

- .travis.yml
- nmake-dll-x86.bat
- nmake-dll.bat
- nmake-lib.bat
- changed nmake-dll.bat and nmake-lib.bat to handle arch options. 
- Travis-CI builds include Win32 and WIn64 nmake.
- Added caching for brew builds to speed up builds.
> Travis-CI build & nmake batch file updates

- bindings/python/keystone/keystone.py
Some platforms split *.so into -devel, which then requires the python library to be patched to load libkeystone.so.0 instead of libkeystone.so.
Welcome for input to better solve this issue.
> bindings/python: attempt to load versioned library

- bindings/python/setup.py
Otherwise `python setup.py build` can't work when keystone is not installed.
> Remove import of keystone in setup.py

- kstool/CMakeLists.txt
- kstool/getopt.c
- kstool/getopt.h
- kstool/kstool.cpp
Using -b option, kstool will print the encoded instructions to stdout
in binary format.
For example:
```
kstool -b arm64 "CCMP X0, X1, 4, EQ" 0xcafebaba | xxd
00000000: 0400 41fa                                ..A.
```
For `getopt`, this commit reuse the [getopt.c](https://github.com/aquynh/capstone/blob/next/cstool/getopt.c) from capstone-engine.
> Add binary output option (-b) to kstool

- llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp
- suite/regress/arm_sym_resolver.py
- suite/regress/arm_sym_resolver_thumb.py
When branching backwards in thumb to a sym_resolved symbol, the instruction was always encoded as "bl #0" because negative offset were rejected.
I've added tests for both ARM32 and THUMB where sym_resolve is used for jumping back & forward. The THUMB test fails without the fix in ARMAsmBackend.cpp and passes with the fix.
> test+fix thumb backwards branching with sym_resolver (#355)

- CMakeLists.txt
- include/keystone/keystone.h
- llvm/keystone/CMakeLists.txt
With these improvements you are now able to include keystone in your CMake project with `add_subdirectory` and not have all the fuzzers and uninstall.
It also fixes an issue where things are marked as `__declspec(dllexport)`, even when keystone is built as a static library. This is backwards compatible and will behave as it currently behaves if you don't define `KEYSTONE_STATIC`.
> CMake fixes

- bindings/python/debian/changelog
- debian/changelog
I just pulled the latest keystone sources and noticed that you'd tagged release 0.9.2 without updating the Debian packaging.
> Update Debian packaging for 0.9.2

- bindings/csharp/Keystone.Net/.nuget/Keystone.Net.targets
Targeting .NET Standard implies a desire to be cross-plat, so I've created a targets file that can be placed in a NuGet package alongside compiled keystone dynamic libraries for win-x64, win-x86, linux-x64, and osx-x64. Doing this makes it so that the projects consuming the NuGet package can be run on any of those operating systems with `dotnet build` and `dotnet run` and projects can be built for any other system with `dotnet publish --os TARGET_OS`.
Working example of this package consumed in [this repo](https://github.com/jonko0493/Wiinject) and can be downloaded from an Azure DevOps feed [here](https://dev.azure.com/jonko0493/haroohie-public/_packaging?_a=package&feed=wiinject&view=overview&package=Keystone.Net&version=0.9.4&protocolType=NuGet).
> Make C# binding cross-plat through better NuGet packaging

- bindings/haskell/README.md
- bindings/haskell/keystone.cabal
Cabal adds C source files to the sdist automatically, but not the
contents of header dirs. That must be done explicitly. With this
change,`cabal sdist` will produce a buildable sdist (previously, it
would fail due to missing a header file).
> Haskell bindings: fix sdist generation/pkg install
